site_name: 我的技术展示-光轮电子
nav:
- 主页: index.md
- ATouch:
  - ATouch: atouch/index.md
  - ATouch 使用说明: atouch/guide.md
- OPENVIO:
  - OPENVIO: openvio/index.md
  - OPENVIO SLAM: openvio/slam_vio.md
  - HARDWARE: openvio/hardware.md
- GLMocap:
  - GLMocap: mocap/index.md  
  - GLMocap 使用说明: mocap/guide.md
- GLDrone:
  - 主页: gldrone/index.md    
  - GLDrone飞行器: gldrone/gldrone.md     
  - GLPX4-F4: gldrone/glpx4-f4.md    
  - GLPX4-H7: gldrone/glpx4-h7.md     
  - GLPX4-R329: gldrone/glpx4-r329.md    
  - GLPX4-ESP32: gldrone/glpx4-esp32.md      
  - GLDRONE-ESP32: gldrone/gldrone-esp32.md   
- CodeNotes:
  - CodeNotes: codenotes/index.md 
- CXK开发板:
  - CXK开发板: cxk/index.md  
- SLAM小车:
  - SLAM小车: slam/index.md  
- 其他软硬件项目:
  - PX4硬件方案: px4/index.md  
  - OPENMVS3: openmvs3/index.md    
  - ATouch(V3s): atouchv3s/index.md      
- 数学:
  - 矩阵: math/matrix.md
  - 数学符号: math/symbol.md
- 关于: 
  - 关于本站: about/about.md
  - 捐赠: about/donate.md
  
theme:
  name: 'material'
  logo: images/logo.jpg
  
markdown_extensions:
  - admonition
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde 
extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'  
# extra_css:
#   - css/style.css
copyright: 'Copyright &copy; 光轮电子 <a href="https://beian.miit.gov.cn">冀ICP备20000720号</a> '